# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e657565a7b4d4cb375f81132bdc7bc004dd0a99fc31fdc09200a494fdc15d646b8af7f9b5ac05af78ddffab7e7cbee4abfce066cc0f663c584449e0be25bb4ef

test:
  secret_key_base: 983324836dae26a471f6dc16aee51d6988a54baae9383c6e9ad7a066d84e29f3844106af7a4696eb0cd04870187a445914fb88c1898705f3e99f2f558ec15dda

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
